rocm5.3 ci
pytorch/FBGEMM pull request #1543
Opened 2023-01-12 16:22 UTC by liligwu

- Upgrade ROCm CI to 5.3.
- BF16 tests are disabled since BF16 methods are not implemented in ROCm.
- More managed memory allocation tests are skipped for ROCm.
- Add ROCm installation instructions in README.

2023-01-12 17:07 UTC, shintaro-iwasaki reviewed
Thanks for your contributions! Please ping me when this PR gets ready (e.g., after fixing Linter issues).

2023-01-12 18:04 UTC, liligwu commented on fbgemm_gpu/test/split_table_batched_embeddings_test.py
> +                ] * T
> 

Thank you for your suggestions. The logic was changed.

2023-01-23 17:19 UTC, liligwu commented
> Thanks for your contributions! Please ping me when this PR gets ready (e.g., after fixing Linter issues).

Hi @shintaro-iwasaki , regarding the linter issues, I can shorten the lines like https://github.com/pytorch/FBGEMM/blob/8184b8e84dfb69afb1b01712fa98ed9c81fd6f67/fbgemm_gpu/test/split_table_batched_embeddings_test.py#L161 but I don't think we can shorten the lines like https://github.com/pytorch/FBGEMM/blob/8184b8e84dfb69afb1b01712fa98ed9c81fd6f67/fbgemm_gpu/test/split_table_batched_embeddings_test.py#L170. Do you have any suggestions? Thank you.

2023-01-23 17:26 UTC, shintaro-iwasaki commented
I might be misunderstanding your question so please correct me; I don't think Linter asks you to change a line including `MANAGED_CACHING`. 

Just in case: for example, one of the Linter errors is

```diff
--- /home/runner/work/FBGEMM/FBGEMM/fbgemm_gpu/test/split_table_batched_embeddings_test.py
+++ /home/runner/work/FBGEMM/FBGEMM/fbgemm_gpu/test/split_table_batched_embeddings_test.py
@@ -162,9 +162,7 @@
             compute_device = split_table_batched_embeddings_ops.ComputeDevice.CPU
         elif TEST_WITH_ROCM:
             # ROCm managed momory allocation is under development
-            managed = [
-                split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE
-            ] * T
+            managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
         elif use_cache:
             managed = [
                 split_table_batched_embeddings_ops.EmbeddingLocation.MANAGED_CACHING
```

It indicates that your current code is
```py
             compute_device = split_table_batched_embeddings_ops.ComputeDevice.CPU
         elif TEST_WITH_ROCM:
             # ROCm managed momory allocation is under development
             managed = [
                 split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE
             ] * T
         elif use_cache:
             managed = [
                 split_table_batched_embeddings_ops.EmbeddingLocation.MANAGED_CACHING
```
and the Linter asks you to change your code to
```py
             compute_device = split_table_batched_embeddings_ops.ComputeDevice.CPU
         elif TEST_WITH_ROCM:
             # ROCm managed momory allocation is under development
             managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
         elif use_cache:
             managed = [
                 split_table_batched_embeddings_ops.EmbeddingLocation.MANAGED_CACHING
```

2023-01-23 17:32 UTC, liligwu commented
> I might be misunderstanding your question so please correct me; I don't think Linter asks you to change a line including `MANAGED_CACHING`.
> 
> Just in case: for example, one of the Linter errors is
> 
> ```diff
> --- /home/runner/work/FBGEMM/FBGEMM/fbgemm_gpu/test/split_table_batched_embeddings_test.py
> +++ /home/runner/work/FBGEMM/FBGEMM/fbgemm_gpu/test/split_table_batched_embeddings_test.py
> @@ -162,9 +162,7 @@
>              compute_device = split_table_batched_embeddings_ops.ComputeDevice.CPU
>          elif TEST_WITH_ROCM:
>              # ROCm managed momory allocation is under development
> -            managed = [
> -                split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE
> -            ] * T
> +            managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
>          elif use_cache:
>              managed = [
>                  split_table_batched_embeddings_ops.EmbeddingLocation.MANAGED_CACHING
> ```
> 
> It indicates that your current code is
> 
> ```python
>              compute_device = split_table_batched_embeddings_ops.ComputeDevice.CPU
>          elif TEST_WITH_ROCM:
>              # ROCm managed momory allocation is under development
>              managed = [
>                  split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE
>              ] * T
>          elif use_cache:
>              managed = [
>                  split_table_batched_embeddings_ops.EmbeddingLocation.MANAGED_CACHING
> ```
> 
> and the Linter asks you to change your code to
> 
> ```python
>              compute_device = split_table_batched_embeddings_ops.ComputeDevice.CPU
>          elif TEST_WITH_ROCM:
>              # ROCm managed momory allocation is under development
>              managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
>          elif use_cache:
>              managed = [
>                  split_table_batched_embeddings_ops.EmbeddingLocation.MANAGED_CACHING
> ```

Oops. Sorry, I use a local lint to analyze the code, and it gives me the "lines too long" warnings. 
I'll push the changes soon. Thank you.

2023-01-24 15:12 UTC, liligwu commented
Hi @shintaro-iwasaki .  Would you please review the PR again?

2023-01-24 17:00 UTC, shintaro-iwasaki requested changes
Thanks! I left some comments, but overall this PR looks good to me!
Once all the comments are addressed, please let me import and merge this PR.

2023-01-24 20:02 UTC, liligwu commented on fbgemm_gpu/test/split_table_batched_embeddings_test.py
> +            managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
The logic was changed.

2023-01-24 20:05 UTC, liligwu commented on fbgemm_gpu/test/split_table_batched_embeddings_test.py
> +            managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
The same as above.

2023-01-24 20:05 UTC, liligwu commented on fbgemm_gpu/test/split_table_batched_embeddings_test.py
> +            managed = [split_table_batched_embeddings_ops.EmbeddingLocation.DEVICE] * T
The same as above.

2023-01-24 20:06 UTC, liligwu commented on fbgemm_gpu/test/split_table_batched_embeddings_test.py
> +        # ROCm managed momory allocation is under development
Thank you for the correction.

2023-01-24 20:06 UTC, liligwu commented on fbgemm_gpu/README.md
> +The remaining steps are the same as "in the container" section.
It's removed.

2023-01-24 20:06 UTC, liligwu commented on fbgemm_gpu/README.md
> +FBGEMM_GPU supports running on AMD (ROCm) devices. A Docker container is recommand for setting up the ROCm environment. The installation on bare metal is also available. ROCm5.3 is used as an example
It's corrected.

2023-01-24 20:55 UTC, shintaro-iwasaki approved these changes
Looks good to me! Thank you for your contribution!

It would take some time to merge it, but I will merge this PR soon.

2023-01-24 21:14 UTC, brad-mengchi approved these changes

2023-01-24 21:58 UTC, liligwu commented
> Looks good to me! Thank you for your contribution!
> 
> It would take some time to merge it, but I will merge this PR soon.

Thank you for your help.

2023-01-25 20:58 UTC, closed without merging